# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: server

frameworkVersion: "3"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:*"
        - "ssm:GetParameter"
        - "ssm:GetParameters"
        - "ssm:GetParametersByPath"
      Resource:
        - "*"

custom:
  serverless-offline-ssm:
    stages:
      - local
    ssm:
      "/solarhub-influxdb-token": "test-token"
      "/solarhub-influxdb-url": "http://influxDb:8086/"

plugins:
  - serverless-offline-ssm
  - serverless-offline

# The `functions` block defines what code to deploy
functions:
  power:
    handler: build/handler.power
    events:
      - http:
          path: power
          method: post
          cors: true
    environment:
      bucket: Power
      org: SolarHub
      token: ${ssm:/solarhub-influxdb-token}
      url: ${ssm:/solarhub-influxdb-url}
